### ISSUE TITLE
Warning: session_start(): Cannot send session cache limiter

### ISSUE THREAD

**Issue by konorws** [copona/copona#217]
When I run the application in my development environment, I get a bunch of notifications about the headers already being sent.

I want to draw attention to the fact that the original OpenCart in the same environment does not have such problems

http://joxi.ru/BA0oKZeSJoRLE2

The easiest solution is to add 
`ob_start();`
in index.php files
But it is better to find out what the problem is and what is the name of the information

**Comment by arnisjuraga** [comment]
There was a bug in copona/core package. Created database.php file contained empty whitespace character at the beginning of file.

Fixed by update in composer package https://github.com/copona/core/commit/eb741d46b59a4b63d8ea1a897b50d6f76b3e734f 

To update it, run :

`composer update copona/core`

and then, please, try to run installation again, 
or just remove a white-space character before opening `<?php ` tag in: 

`/config/[dev | your_env_name]/database.php` 

file.

All new installations must be fixed now.
