### ISSUE TITLE
Vqmod or Ocmod?

### ISSUE THREAD

**Issue by prhost** [copona/copona#47]
For me in reality the two are bad, and that should not exist in the future Copona. But if you want me to put it, I'd like to know which one to put, and also discuss the difference, which is better 😈

**Comment by arnisjuraga** [comment]
VQmod would be nice to keep. For the compatibility at the meantime.

It's much straight forward. 
- keeps modules in .xml files
- uses cache (but can be configured to devMode to rewrite files every time)
- uses nice log files with a log rotation default.

OCMod, on the other hand:
- requires manual "refresh" in admin
- in fact.... that's it. This one disadvantage is more than enough to drop it completely :)

**Comment by prhost** [comment]
You know you both lose a lot of performance. I've studied the vqmod code for a while, and it does a lot to process a modification. It searches all the time by file, uses glob, check modifications by timestamp, and works with reading and writing files in real time. I do not know what ocmod is, but it's likely to be similar.

It also has the XML question, which is to learn more a language. The question of spacing and absolute position of the code if not vqmod/ocmod does not think to modify.

But if it is to keep one of the two, I vote on vqmod because I understand it more.

**Comment by arnisjuraga** [comment]
Vqmod does not rewrite files everytime, if devmode is off.

So performance with cached files is acceptable.

The idea itself - to use search-replace in source,  is 
- good, because its simple learnable and usable
- very very bad, because of dependencies and debugging and so on.

So, we will get rid of it once for all in the future! But untill then - for modules compatibility and lack of alternative plugins engine, we should keep Vqmod.

**Comment by arnisjuraga** [comment]
Let's stick with VQMOD and only! 
CMOD will not be supported and will be removed completely in the future.
