### ISSUE TITLE
Minimum Requirements

### ISSUE THREAD

**Issue by lucasjkr** [copona/copona#70]
Is there a reason that we have to target PHP 5.4 as the minimum version? It's long since out of date, most web hosts will use PHP 5.6 or PHP 7.

If we use a later target, we can use PHP's password_hash and password_verify functions, rather than the md5 hashing that is used in Opencart.

And if we target PHP7, we can do away with having to supported the once deprecated and now removed mysql_ functions, and just have users with MySQL databases use the mysqli extension, or PDO.

Thoughts?

**Comment by arnisjuraga** [comment]
For sure!

PHP 5.4 has been here only because of Opencart base itself. 
I am using Opencart on >=5.6, and there are no compatibility issues. Although, I have noticed some strange requirements into `cli_install.php file`, but as we do not use cli install and it has many bugs anyway, there are no need to support it there anyway. (by the way - I have fixed cli_install.php just for fun, and lately done some installation tests successfully!)

Supporting only PHP7, IMHO, is too early. So let's stick with minimum >=5.6?

**Comment by lucasjkr** [comment]
I agree with targeting 5.6 until December 31, 2018

http://php.net/supported-versions.php

**Comment by arnisjuraga** [comment]
OC 3 has moved to PHP 7+.
And we can now easily add this too.
https://github.com/opencart/opencart/commit/6e30f9bd034fb721af94ee2f6e9d50d4f00dd94c

**Comment by ADDCreative** [comment]
PHP 5.6 security support lasts slightly longer than PHP 7.0. If you are going to up the minimum version it needs to be 7.1.

**Comment by arnisjuraga** [comment]
I have been using Copona with 7.2 for a while. And this is my test env. version. 
Although it should work with older versions.
We can go with 7.2.


🤣 https://github.com/opencart/opencart/issues/6437#issuecomment-370161814
