### ISSUE TITLE
Create simple SQL queries log for debug purpose.

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#84]
https://github.com/copona/copona/pull/80
- turn it on/off by using some debug constant in config.php
- should have log of execution time also

**Comment by lucasjkr** [comment]
In my installation branch, I'm creating the debug constant.

I need to investigate logging a little more - it appears that turning on the general query log turns it on all for all databases, rather than only the one we are executing queries against.  I need to create another db on my dev machine and see what happens.

Solution might just be turn logging off in the destructor.

I probably won't get to it tonight, but can continue tomorrow, unless someone else does it before hand :)

**Comment by arnisjuraga** [comment]
We have already `DEBUG` constant in config
https://github.com/copona/copona/blob/master/config.sample.php?ts=2 . I am using it for `pr()` and `prd()` functions (located in šystem/helpers/debug.php`. 

Just add `DEBUG_SQL` or something like this.

**Comment by CZechBoY** [comment]
What about https://github.com/BurdaPraha/oc_tracy?
It logs queries into debug panel.

**Comment by arnisjuraga** [comment]
Welcome, @CZechBoY 
Yes, we are already discussing it here #141  and #138, a little bit about Logger: #108 
So, I am closing this issue then, as we are planning to _steroidize_ logging/debug bar, and continue a discussion on linked issues. Feel free to collaborate!
